### ISSUE TITLE
Hey there!

### ISSUE THREAD

**Issue by fesnandu** [AlbinoDrought/LoveBoot#1]
Hey, hello there.

I was checking on your autoplayer for lovebeat and found it pretty interesting.
I downloaded it and tried running it but it seemed not to work with LoveRitmo (a brazilian lovebeat server). Been wondering if you could make the effort and tryna build one for LoveRitmo, would you?!

Cheers, thanks in advance,
Bible.

**Comment by fesnandu** [comment]
http://loveritmo.softnyxbrasil.com/

**Comment by AlbinoDrought** [comment]
I'll work on this - do you know if the layout is the same? If so I can just
add it to the process list.

EDIT: It works on LoveRitmo, on the basic modes at least - I can't understand any of the options so I do not know how to go to harder songs or modes.

**Comment by AlbinoDrought** [comment]
Fixed with latest commit, added process picker - works on LoveRitmo. See https://github.com/AlbinoDrought/LoveBoot/releases/tag/v0.01b

**Comment by fesnandu** [comment]
Oh, thank you kind sir, but still, it doesn't work with LR. I press all the buttons but nothing happens... F7, F8, F9, F10... :(

**Comment by AlbinoDrought** [comment]
Are you in windowed mode? Right now that is the only way it works. If not,
do you see the options toggling in the overlay (when you press F10, do you
see the face in the top right change colors?). If not, try pressing Fn+F10
if you have that key.

**Comment by fesnandu** [comment]
No, I'm not. And it seems I can't change it. Current resolution is 1366x768 - does it affect the software?

**Comment by AlbinoDrought** [comment]
Yeah, the game (at least steam version) forces windows mode unless your
resolution is greater than the window size - at x768 it is always on. I'll
try to work on a fix for this, but I'm not sure when I will get it working.

**Comment by fesnandu** [comment]
Alright, appreciate that! Thank you very much!

**Comment by fesnandu** [comment]
Bro, my work's PC runs it smoothly. Love it. BUT it still misses spaces and it's got a bit o' delay to press the arrows.
