### ISSUE TITLE
when active boot in Love Ritmo I disconnect

### ISSUE THREAD

**Issue by prz31** [AlbinoDrought/LoveBoot#13]
when active boot in Love Ritmo I disconnect

**Comment by AlbinoDrought** [comment]
Just played for 4+ rounds without an issue, can't reproduce (latest version of LoveRitmo and LoveBoot). 4-key and 8-key, auto-ready or not.

**Comment by prz31** [comment]
My friends and I are disconnect when activated boot But you can play without any issues  :(

**Comment by prz31** [comment]
Really I can't activete boot because in LR brazil disconnect too I don't know why u_u could you help ?

**Comment by prz31** [comment]
hey friend really Loveboot don't work in LR :C disconnect
