### ISSUE TITLE
How can we edit your program with the source you put for us?

### ISSUE THREAD

**Issue by luissuniga** [AlbinoDrought/LoveBoot#27]
please if you could explain so I can try to fiz that bar hit

**Comment by AlbinoDrought** [comment]
The main lines of code relevant to this issue are:

https://github.com/AlbinoDrought/LoveBoot/blob/master/LoveBoot/BotLogic.cs#L211 (more-so the barcropsettings)

BarCropSettings is a rectangular area of the screenshot that is cut out and then searched for the bar. This can be changed without modifying the code - see `bar.lvb` or https://github.com/AlbinoDrought/LoveBoot/blob/master/LoveBoot/BotLogic.cs#L127

The main issue, though, is probably around here: https://github.com/AlbinoDrought/LoveBoot/blob/master/LoveBoot/BotLogic.cs#L441

This is the part of the code that actually searches the cut out image for the bar, and then presses the space key. Right now, it just presses the space bar as soon as it sees it, and then waits 50ms. This is probably not optimal - a better way would probably be to calculate the time it would take for the bar to go from where it is to the "perfect hit" area, wait that much time, and then press the space bar.

**Comment by luissuniga** [comment]
But I mean what do I need to do it? I need to edit that source files and compile again don't i?

**Comment by AlbinoDrought** [comment]
The easiest way to do that would be to get [Visual Studio Community Edition](https://www.visualstudio.com/vs/community/). It's free for (at least) personal use, and that should be fine for this project.

Once you have it setup, you should be able to open the `LoveBoot.sln` solution file in this repo to open the project and begin editing.

**Comment by luissuniga** [comment]
okay, thank you I'll try it
