### ISSUE TITLE
Error when compiling source. Anyone have it without the text spam?

### ISSUE THREAD

**Issue by sirioth** [AlbinoDrought/LoveBoot#32]
It gives error to me when compiling.

**Comment by AlbinoDrought** [comment]
Include more specific compilation errors. Most errors are due to no emgu verison being referenced.

https://github.com/AlbinoDrought/LoveBoot/issues/23#issuecomment-254328551

**Comment by sirioth** [comment]
Yes, it's something about emgu

**Comment by sirioth** [comment]
And i'm really bad with programming it took me long enough to know how to do the basics and try to remove the spam text
