### ISSUE TITLE
Can the messages be removed or altered?

### ISSUE THREAD

**Issue by barbs88** [AlbinoDrought/LoveBoot#35]
Hello,

nice work on this, but is there any process to remove the chat spam? thanks so much

**Comment by AlbinoDrought** [comment]
The messages have been added to this version to stop abuse. It would be possible to remove them by re-compiling it, see these relevant tickets about compiling:

https://github.com/AlbinoDrought/LoveBoot/issues/32

https://github.com/AlbinoDrought/LoveBoot/issues/31

https://github.com/AlbinoDrought/LoveBoot/issues/27

**Comment by barbs88** [comment]
Thanks so much for for the reply :)

**Comment by barbs88** [comment]
Can you tell wheres the code for the spam messages and how to compile?it will be much appreciated,  i have downloaded VS 2017 Community

**Comment by AlbinoDrought** [comment]
The portion of the program that sends messages is located here: https://github.com/AlbinoDrought/LoveBoot/blob/master/LoveBoot/BotLogic.cs#L389

**Comment by barbs88** [comment]
really appreciated, thanks, i tried to compile it but when i run the exe the process becomes not responding or it just goes away, no program is running, anyways, another one is how to adjust the time when pressing the spacebar?  you said it is located here

> The main issue, though, is probably around here: https://github.com/AlbinoDrought/LoveBoot/blob/master/LoveBoot/BotLogic.cs#L441
> 
> This is the part of the code that actually searches the cut out image for the bar, and then presses the space key. Right now, it just presses the space bar as soon as it sees it, and then waits 50ms. This is probably not optimal - a better way would probably be to calculate the time it would take for the bar to go from where it is to the "perfect hit" area, wait that much time, and then press the space bar.


but i cant find where to adjust the timing or milliseconds,

another one, i want to adjust the timing of pressing the F5, to a bit longer, maybe add 5 seconds, where is the line for that? thanks so much

**Comment by barbs88** [comment]
> but i cant find where to adjust the timing or milliseconds,
> 
> another one, i want to adjust the timing of pressing the F5, to a bit longer, maybe add 5 seconds, where is the line for that? thanks so much

i think i found it on line 69 and 72
